'use client';
import { useState, useEffect } from 'react';

export default function InventoryReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [generating, setGenerating] = useState(false);
  const [detail, setDetail] = useState<any>(null);
  const [title, setTitle] = useState('');

  const load = async () => {
    const res = await fetch('/api/reports?type=inventory');
    if (res.ok) { const d = await res.json(); setReports(d.reports); }
  };
  useEffect(() => { load(); }, []);

  async function generate() {
    setGenerating(true);
    const res = await fetch('/api/reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: title || undefined }) });
    if (res.ok) { const d = await res.json(); setDetail(d.data); load(); }
    setGenerating(false);
  }

  return (
    <div className="fade-in">
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 700 }}>📊 Inventory Reports</h1>
        <div style={{ display: 'flex', gap: '.75rem', alignItems: 'center' }}>
          <input className="input" style={{ width: 200 }} placeholder="Report title (optional)" value={title} onChange={e => setTitle(e.target.value)} />
          <button className="btn btn-primary" onClick={generate} disabled={generating}>{generating ? 'Generating…' : '📋 Generate Report'}</button>
        </div>
      </div>

      {detail && (
        <div className="card" style={{ marginBottom: '1.5rem', borderLeft: '4px solid var(--accent)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem', flexWrap: 'wrap', gap: '.5rem' }}>
            <h2 style={{ fontWeight: 600 }}>Latest Snapshot</h2>
            <div style={{ display: 'flex', gap: '1.5rem' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--info)' }}>{detail.summary?.total_products}</div>
                <div style={{ fontSize: '.75rem', color: 'var(--text-muted)' }}>Products</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--success)' }}>LKR {(detail.summary?.total_value || 0).toLocaleString()}</div>
                <div style={{ fontSize: '.75rem', color: 'var(--text-muted)' }}>Total Value</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--danger)' }}>{detail.summary?.low_stock_count}</div>
                <div style={{ fontSize: '.75rem', color: 'var(--text-muted)' }}>Low Stock</div>
              </div>
            </div>
          </div>
          <div className="table-wrap">
            <table>
              <thead><tr><th>Product</th><th>Category</th><th>Cost (LKR)</th><th>Price (LKR)</th><th>Stock</th><th>Value</th></tr></thead>
              <tbody>
                {detail.products?.map((p: any) => (
                  <tr key={p.id}>
                    <td style={{ fontWeight: 500 }}>{p.name}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{p.category_name || '—'}</td>
                    <td>{p.cost_price.toFixed(2)}</td>
                    <td style={{ color: 'var(--success)' }}>{p.selling_price.toFixed(2)}</td>
                    <td style={{ color: p.quantity <= p.low_stock_threshold ? 'var(--danger)' : 'var(--text-primary)', fontWeight: p.quantity <= p.low_stock_threshold ? 700 : 400 }}>
                      {p.quantity} {p.unit}
                    </td>
                    <td>LKR {(p.cost_price * p.quantity).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <div className="card">
        <h2 style={{ fontWeight: 600, marginBottom: '1rem' }}>Report History</h2>
        <div className="table-wrap">
          <table>
            <thead><tr><th>Title</th><th>Date</th><th>Generated By</th><th>Action</th></tr></thead>
            <tbody>
              {reports.map(r => (
                <tr key={r.id}>
                  <td style={{ fontWeight: 500 }}>{r.title}</td>
                  <td style={{ color: 'var(--text-secondary)' }}>{r.report_date}</td>
                  <td style={{ color: 'var(--text-muted)' }}>{r.manager_name}</td>
                  <td><button className="btn btn-secondary btn-sm" onClick={() => setDetail(JSON.parse(r.data_json))}>View</button></td>
                </tr>
              ))}
              {!reports.length && <tr><td colSpan={4} style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>No reports yet</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
